sudo: required

services:
  - docker

env:
- CHANGE_MINIKUBE_NONE_USER=true

before_install:
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update; sudo apt-get install kubectl
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl; chmod +x kubectl; sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64; chmod +x minikube; sudo mv minikube /usr/local/bin/
  - sudo minikube start --vm-driver=none --bootstrapper=localkube
  - minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
  
install: true

script:
  - echo "Testing MiniKube deployment"
  - mkdir minikube_test; cd minikube_test
  - kubectl get all
  - export SOLACE_KUBERNETES_QUICKSTART_REPO="$TRAVIS_REPO_SLUG"; export SOLACE_KUBERNETES_QUICKSTART_BRANCH="$TRAVIS_BRANCH"
  - wget https://raw.githubusercontent.com/$SOLACE_KUBERNETES_QUICKSTART_REPO/$SOLACE_KUBERNETES_QUICKSTART_BRANCH/scripts/configure.sh
  - chmod 755 configure.sh
  - ./configure.sh -p admin -i gcr.io/capable-stream-180018/solace-pubsub-standard:8.10.0.1057
  - cd solace-kubernetes-quickstart/solace
  - ../../helm/helm install . -f values.yaml
  - kubectl get statefulset,svc,pods,pvc,pv --show-labels
  - echo "Waiting for cluster to become active"
  - "travis_wait 30 sleep 1800 &"
  - until kubectl get statefulset,svc,pods,pvc,pv --show-labels | grep solace-0 | grep -m 1 -E '1/1'; do sleep 10; done
  - kubectl get statefulset,svc,pods,pvc,pv --show-labels
  - url="$(kubectl get statefulset,svc,pods,pvc,pv --show-labels | grep LoadBalancer | awk '{print $4}')"; echo $url
  - curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
  - tar -xvf SDKPERF_C_LINUX64
  - pubSubTools/sdkperf_c -cip=$url -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
